# The desktop nix build's binaries (xray / sing-box / tun2socks / hev-socks5-tunnel
# / geodat2srs), fetched at the EXACT pinned versions (fixed-output, reproducible).
# The prebuilt ones come from GitHub releases (unzip / untar / raw binary); their
# release-asset layout is read from scripts/binaries.json (the shared catalog,
# single source of truth with the fetch scripts). geodat2srs ships no release
# artifacts, so it is built from source via buildGoModule at the pinned
# GEODAT2SRS_REV. Archive hashes live in scripts/binary-hashes.json (regenerated by
# scripts/update-binary-hashes.sh).
{
  pkgs,
  self,
  version,
}: let
  inherit (pkgs) lib;
  catalog = builtins.fromJSON (builtins.readFile (self + "/scripts/binaries.json"));
  binaryHashes = builtins.fromJSON (builtins.readFile (self + "/scripts/binary-hashes.json"));

  # The desktop nix build targets linux-amd64; pull that arch's asset from the
  # catalog and compose the standard GitHub release URL.
  arch = "linux-amd64";
  coreSrc = name: let
    c = catalog.${name};
    tag = version.pinnedVersion c.version_var;
    ver = lib.removePrefix "v" tag;
    file = builtins.replaceStrings ["{ver}"] [ver] c.assets.${arch}.file;
  in
    pkgs.fetchurl {
      url = "https://github.com/${c.repo}/releases/download/${tag}/${file}";
      hash = binaryHashes.${name};
    };

  xraySrc = coreSrc "xray";
  tun2socksSrc = coreSrc "tun2socks";
  singboxSrc = coreSrc "sing-box";
  # linux-amd64 ships as a raw static binary (no archive) — installed as-is.
  hevSrc = coreSrc "hev-socks5-tunnel";

  geodat2srsSrc = pkgs.fetchFromGitHub {
    owner = "loss-and-quick";
    repo = "geodat2srs";
    rev = version.geodat2srsRev;
    hash = binaryHashes."geodat2srs-src";
  };

  # geodat2srs has no release artifacts → build from source at the pinned commit
  # (host arch, CGO off → static). Only the desktop `nix build` consumes this; the
  # Android module is script-built, so it builds geodat2srs from the same pinned
  # rev via scripts/fetch-binaries.sh (no nix required there).
  geodat2srsDesktop = pkgs.buildGoModule {
    pname = "geodat2srs";
    version = builtins.substring 0 7 version.geodat2srsRev;
    src = geodat2srsSrc;
    vendorHash = binaryHashes."geodat2srs-vendor";
    subPackages = ["."];
    doCheck = false;
    env.CGO_ENABLED = "0";
  };
in {
  # Assemble the binaries under plain names — the desktop Platform looks for
  # `{KASUMI_BIN_DIR}/{xray,sing-box,tun2socks,hev-socks5-tunnel,geodat2srs}`
  # (src-tauri/src/desktop/paths.rs).
  desktopBinaries =
    pkgs.runCommand "kasumi-desktop-binaries-${version.appVersion}"
    {
      nativeBuildInputs = [
        pkgs.unzip
        pkgs.gnutar
      ];
    }
    ''
      mkdir -p $out/bin tmp && cd tmp
      unzip -j ${xraySrc} xray -d $out/bin
      unzip -j ${tun2socksSrc} -d t2s
      install -m755 "$(find t2s -type f -name 'tun2socks*' | head -1)" $out/bin/tun2socks
      tar xzf ${singboxSrc}
      install -m755 "$(find . -type f -name sing-box | head -1)" $out/bin/sing-box
      install -m755 ${hevSrc} $out/bin/hev-socks5-tunnel
      install -m755 ${geodat2srsDesktop}/bin/geodat2srs $out/bin/geodat2srs
      chmod +x $out/bin/*
    '';
}
