# The proxy cores (xray / sing-box / tun2socks / geodat2srs) for the desktop nix
# build, fetched at the EXACT pinned versions (fixed-output, reproducible). The
# first three are prebuilt static Go archives (unzip / untar); their release-asset
# layout is read from scripts/cores.json (the shared catalog, single source of
# truth with the fetch scripts). geodat2srs ships no release artifacts, so it is
# built from source via buildGoModule at the pinned GEODAT2SRS_REV. Archive hashes
# live in scripts/core-hashes.json (regenerated by scripts/update-core-hashes.sh).
{
  pkgs,
  root,
  version,
}:
let
  lib = pkgs.lib;
  catalog = builtins.fromJSON (builtins.readFile (root + "/scripts/cores.json"));
  coreHashes = builtins.fromJSON (builtins.readFile (root + "/scripts/core-hashes.json"));

  # The desktop nix build targets linux-amd64; pull that arch's asset from the
  # catalog and compose the standard GitHub release URL.
  arch = "linux-amd64";
  coreSrc =
    name:
    let
      c = catalog.${name};
      tag = version.coreVersion c.version_var;
      ver = lib.removePrefix "v" tag;
      file = builtins.replaceStrings [ "{ver}" ] [ ver ] c.assets.${arch}.file;
    in
    pkgs.fetchurl {
      url = "https://github.com/${c.repo}/releases/download/${tag}/${file}";
      hash = coreHashes.${name};
    };

  xraySrc = coreSrc "xray";
  tun2socksSrc = coreSrc "tun2socks";
  singboxSrc = coreSrc "sing-box";

  geodat2srsSrc = pkgs.fetchFromGitHub {
    owner = "loss-and-quick";
    repo = "geodat2srs";
    rev = version.geodat2srsRev;
    hash = coreHashes."geodat2srs-src";
  };

  # geodat2srs has no release artifacts → build from source at the pinned commit
  # (host arch, CGO off → static). Only the desktop `nix build` consumes this; the
  # Android module is script-built, so it builds geodat2srs from the same pinned
  # rev via scripts/fetch-cores.sh (no nix required there).
  geodat2srsDesktop = pkgs.buildGoModule {
    pname = "geodat2srs";
    version = builtins.substring 0 7 version.geodat2srsRev;
    src = geodat2srsSrc;
    vendorHash = coreHashes."geodat2srs-vendor";
    subPackages = [ "." ];
    doCheck = false;
    env.CGO_ENABLED = "0";
  };
in
{
  # Assemble the four cores under plain names — the desktop Platform looks for
  # `{KASUMI_BIN_DIR}/{xray,sing-box,tun2socks,geodat2srs}` (src-tauri/src/desktop/paths.rs).
  desktopCores =
    pkgs.runCommand "kasumi-desktop-cores-${version.appVersion}"
      {
        nativeBuildInputs = [
          pkgs.unzip
          pkgs.gnutar
        ];
      }
      ''
        mkdir -p $out/bin tmp && cd tmp
        unzip -j ${xraySrc} xray -d $out/bin
        unzip -j ${tun2socksSrc} -d t2s
        install -m755 "$(find t2s -type f -name 'tun2socks*' | head -1)" $out/bin/tun2socks
        tar xzf ${singboxSrc}
        install -m755 "$(find . -type f -name sing-box | head -1)" $out/bin/sing-box
        install -m755 ${geodat2srsDesktop}/bin/geodat2srs $out/bin/geodat2srs
        chmod +x $out/bin/*
      '';
}
