#!/usr/bin/env bash
# ============================================================
# scripts/update-core-hashes.sh
# Regenerate scripts/core-hashes.json — the SRI hashes of the desktop
# (linux-amd64) core archives the nix flake fetches (fixed-output). The asset
# layout is read from scripts/cores.json (the shared catalog); versions from
# core-versions.sh. For each prebuilt core it downloads the linux-amd64 archive
# and computes its SRI sha256 (no nix: sha256sum → base64).
#
# geodat2srs is built from source (nix/cores.nix), so its hashes are nix-derived
# (fetchFromGitHub NAR + go-module vendor) and CANNOT be computed here — they are
# preserved as-is from the existing file. Refresh them with `nix build` when
# bumping GEODAT2SRS_REV (paste the expected hash nix reports).
#
# Run after bumping a version in core-versions.sh (the release CI does it
# automatically). Needs curl, sha256sum, xxd, base64, jq — no nix.
#
# Usage: scripts/update-core-hashes.sh
# ============================================================
set -euo pipefail

ROOT="${PROJECT_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
# shellcheck source=scripts/core-versions.sh
. "$ROOT/scripts/core-versions.sh"
CATALOG="$ROOT/scripts/cores.json"
OUT="$ROOT/scripts/core-hashes.json"

need() { command -v "$1" >/dev/null 2>&1 || {
	echo "❌ missing dependency: $1" >&2
	exit 1
}; }
need curl
need sha256sum
need xxd
need base64
need jq

# SRI sha256 of a URL's content (sha256-<base64>), matching nix's fetchurl format.
sri() {
	local hex
	hex=$(curl -fsSL --retry 3 "$1" | sha256sum | cut -d' ' -f1)
	printf 'sha256-%s' "$(echo "$hex" | xxd -r -p | base64 -w0)"
}

echo "→ hashing pinned linux-amd64 core archives (from cores.json)"
core_hashes='{}'
for core in $(jq -r 'keys[] | select(. != "_comment")' "$CATALOG"); do
	vvar=$(jq -r --arg c "$core" '.[$c].version_var' "$CATALOG")
	repo=$(jq -r --arg c "$core" '.[$c].repo' "$CATALOG")
	file=$(jq -r --arg c "$core" '.[$c].assets["linux-amd64"].file' "$CATALOG")
	tag="${!vvar}"
	file="${file//\{ver\}/${tag#v}}"
	url="https://github.com/$repo/releases/download/$tag/$file"
	echo "  • $core $tag"
	core_hashes=$(jq --arg k "$core" --arg v "$(sri "$url")" '. + {($k): $v}' <<<"$core_hashes")
done

# Preserve the nix-derived geodat2srs hashes (can't be recomputed without nix).
g_src=$(jq -r '."geodat2srs-src" // ""' "$OUT" 2>/dev/null || echo "")
g_vendor=$(jq -r '."geodat2srs-vendor" // ""' "$OUT" 2>/dev/null || echo "")

comment="SRI hashes of the desktop (linux-amd64) core archives, for the nix flake's fixed-output fetch. xray/tun2socks/sing-box are GENERATED by scripts/update-core-hashes.sh from scripts/cores.json + scripts/core-versions.sh — do not hand-edit; the release CI regenerates them on a core bump. geodat2srs is built from source (nix/cores.nix): geodat2srs-src (fetchFromGitHub NAR) and geodat2srs-vendor (go-module vendor) are nix-derived and preserved as-is here — refresh them with \`nix build .#kasumi-desktop\` (paste the expected hash) when bumping GEODAT2SRS_REV."

jq -n \
	--arg comment "$comment" \
	--argjson cores "$core_hashes" \
	--arg gsrc "$g_src" \
	--arg gvendor "$g_vendor" \
	'{_comment: $comment} + $cores + {"geodat2srs-src": $gsrc, "geodat2srs-vendor": $gvendor}' \
	>"$OUT"

echo "✅ wrote $OUT"
