#!/usr/bin/env bash
# ============================================================
# scripts/update-core-hashes.sh
# Regenerate scripts/core-hashes.json — the SRI hashes of the desktop
# (linux-amd64) core archives the nix flake fetches (fixed-output). Reads the
# pinned versions from core-versions.sh, downloads each archive, computes its
# SRI sha256 (no nix needed: sha256sum → base64), and writes the JSON.
#
# Run this after bumping a version in core-versions.sh (the release CI does it
# automatically). Needs curl, sha256sum, xxd, base64 — no nix.
#
# Usage: scripts/update-core-hashes.sh
# ============================================================
set -euo pipefail

ROOT="${PROJECT_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
# shellcheck source=scripts/core-versions.sh
. "$ROOT/scripts/core-versions.sh"
OUT="$ROOT/scripts/core-hashes.json"

need() { command -v "$1" >/dev/null 2>&1 || { echo "❌ missing dependency: $1" >&2; exit 1; }; }
need curl
need sha256sum
need xxd
need base64

# SRI sha256 of a URL's content (sha256-<base64>), matching nix's hash format.
sri() {
	local hex
	hex=$(curl -fsSL --retry 3 "$1" | sha256sum | cut -d' ' -f1)
	printf 'sha256-%s' "$(echo "$hex" | xxd -r -p | base64 -w0)"
}

SB_VER="${SINGBOX_VERSION#v}"
xray_url="https://github.com/XTLS/Xray-core/releases/download/${XRAY_VERSION}/Xray-linux-64.zip"
t2s_url="https://github.com/xjasonlyu/tun2socks/releases/download/${TUN2SOCKS_VERSION}/tun2socks-linux-amd64.zip"
sb_url="https://github.com/SagerNet/sing-box/releases/download/${SINGBOX_VERSION}/sing-box-${SB_VER}-linux-amd64.tar.gz"

echo "→ hashing pinned cores (xray ${XRAY_VERSION}, sing-box ${SINGBOX_VERSION}, tun2socks ${TUN2SOCKS_VERSION})"
xray_h=$(sri "$xray_url")
t2s_h=$(sri "$t2s_url")
sb_h=$(sri "$sb_url")

cat > "$OUT" <<EOF
{
  "_comment": "SRI hashes of the desktop (linux-amd64) core archives, for the nix flake's fixed-output fetch. GENERATED by scripts/update-core-hashes.sh from scripts/core-versions.sh — do not hand-edit; the release CI regenerates it when a core version bumps.",
  "xray": "${xray_h}",
  "tun2socks": "${t2s_h}",
  "sing-box": "${sb_h}"
}
EOF

echo "✅ wrote $OUT"
