//! Generate the frontend's runtime defaults (`frontend/src/generated/defaults.ts`)
//! from Rust — the per-protocol blank profile, the backend constants, and the
//! editor dropdown option lists. Single source: every value here lives once in
//! `kasumi-core` (serde defaults, `pub const`s, enum variants) and is emitted, so
//! the frontend never re-types a default. Emitted by `export_generated`,
//! exactly like `bindings.ts` / `schemas.ts`.

use kasumi_core::core::tun_by_core_options;
use kasumi_core::enums::editor_option_lists;
use kasumi_core::profile::{Protocol, empty_profile};
use kasumi_core::state;
use strum::IntoEnumIterator;

/// The committed defaults file the frontend imports.
pub const DEFAULTS_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../frontend/src/generated/defaults.ts"
);

const HEADER: &str = "\
// This file is generated by `cargo run -p kasumi-desktop --bin codegen`. Do not edit it manually.

import type {
\tAdvancedSettings_Serialize,
\tCongestionControl,
\tCoreEngine,
\tFingerprint,
\tFlow,
\tHeaderType,
\tHysteria2Obfs,
\tLogTarget,
\tPacketEncoding,
\tProfile,
\tProtocol,
\tSecurity,
\tSsMethod,
\tTransport,
\tTunEngine,
\tVmessEnc,
} from \"./bindings\";

";

/// The TS element type for each generated option-list const.
fn opts_type(name: &str) -> &'static str {
    match name {
        "PROTOCOL_OPTS" => "Protocol",
        "CORE_ENGINE_OPTS" => "CoreEngine",
        "LOG_TARGET_OPTS" => "LogTarget",
        "NETWORK_OPTS" => "Transport[\"kind\"]",
        "SECURITY_OPTS" => "Security",
        "HEADER_TYPE_OPTS" => "HeaderType",
        "VMESS_ENC_OPTS" => "VmessEnc",
        "SS_METHOD_OPTS" => "SsMethod",
        "CONGESTION_OPTS" => "CongestionControl",
        "FINGERPRINT_OPTS" => "Fingerprint",
        "FLOW_OPTS" => "Flow",
        "PACKET_ENCODING_OPTS" => "PacketEncoding",
        "HYSTERIA2_OBFS_OPTS" => "Hysteria2Obfs",
        _ => "string",
    }
}

/// Render the defaults module.
pub fn render() -> String {
    let mut out = String::from(HEADER);

    // Per-protocol blank profile templates (Record<Protocol, Profile>). Built
    // from `empty_profile` so the per-field defaults come from the structs.
    let mut empties = serde_json::Map::new();
    for proto in Protocol::iter() {
        let wire = serde_json::to_value(proto)
            .ok()
            .and_then(|v| v.as_str().map(str::to_owned))
            .unwrap_or_default();
        let profile = serde_json::to_value(empty_profile(proto, "")).expect("serialize empty");
        empties.insert(wire, profile);
    }
    let empties_json =
        serde_json::to_string_pretty(&serde_json::Value::Object(empties)).expect("pretty empties");
    out.push_str(
        "/** Per-protocol blank profile templates; `meta.id`/`meta.groupId` are filled per draft. */\n",
    );
    out.push_str("export const EMPTY_PROFILES = ");
    out.push_str(&empties_json);
    out.push_str(" as unknown as Record<Protocol, Profile>;\n\n");

    // The default advanced settings (serde defaults of `AdvancedSettings`). The
    // frontend's runtime/seed/test settings build on this so a new field is typed
    // once, in Rust — never re-typed on the frontend.
    let settings =
        serde_json::to_value(state::AdvancedSettings::default()).expect("serialize settings");
    let settings_json = serde_json::to_string_pretty(&settings).expect("pretty settings");
    out.push_str(
        "/** Default advanced settings (serde defaults; the single source of settings defaults). */\n",
    );
    out.push_str("export const DEFAULT_ADVANCED_SETTINGS = ");
    out.push_str(&settings_json);
    out.push_str(" as AdvancedSettings_Serialize;\n\n");

    // Backend constants (single source: `kasumi-core` contract/state).
    out.push_str(
        "/* Backend constants (port-test windows, local ports, probe URLs, log rotation). */\n",
    );
    // Test-core ports are backend-internal now (the daemon leases them from one
    // shared pool); the frontend just names a profile, so they're not exported.
    let nums: [(&str, i64); 3] = [
        (
            "DEFAULT_LOCAL_SOCKS_PORT",
            state::DEFAULT_LOCAL_SOCKS_PORT as i64,
        ),
        (
            "DEFAULT_LOCAL_HTTP_PORT",
            state::DEFAULT_LOCAL_HTTP_PORT as i64,
        ),
        ("DEFAULT_LOG_ROTATE_KB", state::DEFAULT_LOG_ROTATE_KB),
    ];
    for (name, value) in nums {
        out.push_str(&format!("export const {name} = {value};\n"));
    }
    let strs: [(&str, &str); 2] = [
        ("DEFAULT_DELAY_TEST_URL", state::DEFAULT_DELAY_TEST_URL),
        ("DEFAULT_SPEED_TEST_URL", state::DEFAULT_SPEED_TEST_URL),
    ];
    for (name, value) in strs {
        let json = serde_json::to_string(value).expect("string const");
        out.push_str(&format!("export const {name} = {json};\n"));
    }

    // Editor dropdown option lists (wire values, declaration order).
    out.push_str("\n/* Editor dropdown option lists (wire values, in declaration order). */\n");
    for (name, values) in editor_option_lists() {
        let arr = serde_json::to_string(&values).expect("option list");
        out.push_str(&format!(
            "export const {name}: {}[] = {arr};\n",
            opts_type(name)
        ));
    }

    // Per-core TUN-engine options (default + valid engines), derived from the
    // backend's own `resolve_tun`/`default_tun_for` so the settings UI never
    // re-encodes the per-core default or the SingboxTun-is-sing-box-only rule.
    let mut by_core = serde_json::Map::new();
    for o in tun_by_core_options() {
        by_core.insert(
            wire(o.core),
            serde_json::json!({ "default": wire(o.default), "valid": o.valid.into_iter().map(wire).collect::<Vec<_>>() }),
        );
    }
    let by_core_json =
        serde_json::to_string_pretty(&serde_json::Value::Object(by_core)).expect("pretty tun map");
    out.push_str(
        "\n/** Per-core TUN engine options (default + selectable), single-sourced from Rust `resolve_tun`. */\n",
    );
    out.push_str("export const TUN_BY_CORE = ");
    out.push_str(&by_core_json);
    out.push_str(" as Record<CoreEngine, { default: TunEngine; valid: TunEngine[] }>;\n");

    out
}

/// An enum value's serde wire string (single-sourced from its `Serialize`).
fn wire<T: serde::Serialize>(v: T) -> String {
    serde_json::to_value(v)
        .ok()
        .and_then(|x| x.as_str().map(str::to_owned))
        .unwrap_or_default()
}
